sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
  - npm install

script:
  - ng lint
#  - ng test
  - ng build

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "imagestore"
  skip_cleanup: true
after_success:
  - firebase deploy --project imagestore-e1935 --only hosting --token $FIREBASE_TOKEN
